import client from "@/client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainMenu } from "@/components/MainMenu";
import { gql } from "@apollo/client";
import { mapMainMenuItems } from "@/utils/mapMainMenuItems";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let { data } = await client.query({
    query: gql`
      query PageQuery {
        acfOptionsMainMenu {
          mainMenu {
            callToActionButton {
              label
              destination {
                ... on Page {
                  uri
                }
              }
            }
            menuItems {
              menuItem {
                destination {
                  ... on Page {
                    uri
                  }
                }
                label
              }
              items {
                destination {
                  ... on Page {
                    uri
                  }
                }
                label
              }
            }
          }
        }
      }
    `,
  });

  let mainMenuItems = mapMainMenuItems(
    data.acfOptionsMainMenu.mainMenu.menuItems
  );

  let callToAction = data.acfOptionsMainMenu.mainMenu.callToActionButton;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainMenu
          items={mainMenuItems}
          callToActionLabel={callToAction.label}
          callToActionDestination={callToAction.destination.uri}
        />
        {children}
      </body>
    </html>
  );
}
